docRoot                   $VH_ROOT/html
vhDomain                  localhost
enableGzip                1
enableBr                  1

index  {
  useServer               0
  indexFiles              index.php, index.html
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
}

context /  {
  location                $VH_ROOT/html
  allowBrowse             0
}
